### PR TITLE
new style & slight layout changes WIP

### PR DESCRIPTION
**Pull request by lukealford**
Lots of style & design changes, this of course still a WIP anything can change just felt a darker design suited this type of application.

### CODE REVIEW

**Comment by WonaBee** [comment]
A darker design was pretty much what I was working on until I saw your pull request :) And I had a similiar background picked out.

Could you add a screenshot so people can see before it's implemented?

**Comment by lukealford** [comment]
[Here is a little gif screen grab](http://recordit.co/RUWCx7KbW4).

I personally feel it still needs a lot of work, also I feel a sidebar with a full width layout would work better with this, as it gives us more space for statistics and even graphs if we want to go that far.

**Comment by WonaBee** [comment]
Pretty nice, just a couple of things I would change:

- the opacity of the divs is a bit high or change the background-image so it's a tad bit transparent
- the green text color isn't very nice, maybe white underlined (for the player selection)
- the background-color and the border-radius on the player statistic numbers is unnecessary because you have white text and a slightly darker background for that part
- the h2 (Team A wins etc.) should also have a slightly darker background

For the navigation bar I had the idea to make it look like the menu in CS:
for the navbar itself:
```
background: #1a222a; /* Old browsers */  
background: -moz-linear-gradient(left,  #1a222a 0%, #404850 50%, #182128 100%); /* FF3.6+ */  background: -webkit-gradient(linear, left top, right top, color-stop(0%,#1a222a), color-stop(50%,#404850), color-stop(100%,#182128)); /* Chrome,Safari4+ */  
background: -webkit-linear-gradient(left,  #1a222a 0%,#404850 50%,#182128 100%); /* Chrome10+,Safari5.1+ */  
background: -o-linear-gradient(left,  #1a222a 0%,#404850 50%,#182128 100%); /* Opera 11.10+ */  
background: -ms-linear-gradient(left,  #1a222a 0%,#404850 50%,#182128 100%); /* IE10+ */  
background: linear-gradient(to right,  #1a222a 0%,#404850 50%,#182128 100%); /* W3C */  
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#1a222a', endColorstr='#182128',GradientType=1 ); /* IE6-9 */;
```

and for the li:
```
border-left: 1px solid rgb(35,39,43);
border-right: 1px solid rgb(35,39,43);
```

and for li active and hover states:
```
rgba(90,95,100,0.7)
```

Just some thoughts :)

**Comment by lukealford** [comment]
(Y) thanks for the suggestions implementing them now.

**Comment by lukealford** [comment]
[Preview of latest commit](http://recordit.co/zpuBCQ6V4c)

**Comment by lukealford** [comment]
[Preview of darker divs](http://frank.lukealford.me/headshotbox/headshotbox.png)

**Comment by lukealford** [comment]
[Preview of darker divs](http://frank.lukealford.me/headshotbox/headshotbox.png)

**Comment by bugdone** [comment]
I don't know how hard this would be, but could you add a theme switching button?
I really want to have the option to change between the default theme and other themes (some people might not like the dark theme).

**Comment by lukealford** [comment]
I've thought about this as well. I see there is a bit of angularjs in this, maybe we can include this 
https://github.com/fdomig/angular-themer?

**Comment by bugdone** [comment]
Sure, why not? Give it a try, see if it works.

**Comment by lukealford** [comment]
I gave it a try on my end, the module seems to work, no errors or anything but for some reason style's won't change not sure if it was me doing it wrong or not.

**Comment by lukealford** [comment]
Got some an alternative method working.

**Comment by bugdone** [comment]
Looks pretty cool. I like the new buttons and icons, good stuff!
There are some minor issues though:
* On the dark theme, there are some white things left (the Settings header and the Help boxes are still light and contrast with the rest of the page)
* On the light theme, the player stats are dark and the alignment seems to be gone.

**Comment by lukealford** [comment]
# On the light theme, the player stats are dark and the alignment seems to be gone.

I've adjusted the contrast a little bit on one of the recent commits. Not sure what you mean by alignment is gone, I can only use one template file and I've adjusted the template file for the darker theme(theme switcher only swaps styles & sets a cookie for 60 days I think it is). 

Tables only allow so much styling hence the change, both sheets have the same alignments on the stats they are just different colours.

This is something else that I was thinking about, it would be great if we could have separate themes all together, eg have a whole different layout & style. I've been looking into an angular method but can't seem to find any, they all seem to just swap styles.

**Comment by bugdone** [comment]
So I created a branch "themes" where I merged your changes and added on top of them some. Mostly I fixed the light theme to look like before and fixed some Firefox issues.

The alignment I mentioned above was actually the stats tables (which I brought back from the dead).

I feel it's a bit weird that on the dark theme you can't tell from a glance which matches you won or lost (which is nice on the default theme); I also feel draw games look a bit weird highlighted (gray background). Not really sure what's to be done about this.

**Comment by lukealford** [comment]
Ok, so now that you have added a new branch to the main repo, should I just remove this request? and then pull the branch directly from this repo? Or is there another way I should do it, I'd like to get your updates but still be able to have a go at fixing the above that you have mentioned. 

Sorry, this is slightly getting out of my git knowledge hehe.

**Comment by bugdone** [comment]
I merged the themes branch into master.

**Pull request merged**
